spring:
  datasource:
    driver-class-name: "${MESSENGER_DB_DRIVER_NAME:org.postgresql.Driver}"
    url: "${MESSENGER_DB_URL:jdbc:postgresql://localhost:5432/messenger}"
    username: "${MESSENGER_DB_USERNAME:postgres}"
    password: "${MESSENGER_DB_PASSWORD:postgres}"

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: validate
