spring:
  datasource:
    driver-class-name: "${MESSENGER_DB_DRIVER_NAME:org.postgresql.Driver}"
    url: "${MESSENGER_DB_URL:jdbc:postgresql://localhost:5432/messenger}"
    username: "${MESSENGER_DB_USERNAME:postgres}"
    password: "${MESSENGER_DB_PASSWORD:postgres}"

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: validate

messenger:
  tmp-password-ttl: '${TMP_PASSWORD_TTL:600000}'
  twillio:
    account-sid: '${TWILLIO_ACCOUNT_SID:your_sid}'
    auth-token: '${TWILLIO_AUTH_TOKEN:your_token}'
    mes-ser-id: '${MESSAGING_SERVICE_ID:service_id}'
  token:
    ttl: '${TOKEN_TTL: 286000}'
    refresh-ttl: '${REFRESH_TTL: 360000}'
    signing-key: '${JWT_SIGNING_KEY: w2vzolsu74js1wvpj5f0}'